name: kynet
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  connectivity_plus: ^6.0.5
  speed_test_dart: "^1.0.5+0"
  http: ^1.2.2
  flutter_localizations:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  speed_checker_plugin: ^1.0.23
  syncfusion_flutter_gauges: ^26.2.14
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.8
  sensors_plus: ^6.0.1
  get: ^4.6.6
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
